// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMryD6FQz7dIghMsqiCM6GDrKyt91xSzg',
    appId: '1:632640014839:web:d082f80c04b0007d0e06f2',
    messagingSenderId: '632640014839',
    projectId: 'first-project-a31f1',
    authDomain: 'first-project-a31f1.firebaseapp.com',
    databaseURL: 'https://first-project-a31f1-default-rtdb.firebaseio.com',
    storageBucket: 'first-project-a31f1.appspot.com',
    measurementId: 'G-N20XB56R7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVl7yBQG9no9Zjh0IIn1gSPit4d4hrj0w',
    appId: '1:632640014839:android:ddf00b9eea1321850e06f2',
    messagingSenderId: '632640014839',
    projectId: 'first-project-a31f1',
    databaseURL: 'https://first-project-a31f1-default-rtdb.firebaseio.com',
    storageBucket: 'first-project-a31f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTbxkPFWLz6FeEf4iCyjXPWDQE0a-3ARA',
    appId: '1:632640014839:ios:0c6c523bf5b5afcf0e06f2',
    messagingSenderId: '632640014839',
    projectId: 'first-project-a31f1',
    databaseURL: 'https://first-project-a31f1-default-rtdb.firebaseio.com',
    storageBucket: 'first-project-a31f1.appspot.com',
    iosBundleId: 'com.example.app003',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTbxkPFWLz6FeEf4iCyjXPWDQE0a-3ARA',
    appId: '1:632640014839:ios:62de86a0b8ec76a70e06f2',
    messagingSenderId: '632640014839',
    projectId: 'first-project-a31f1',
    databaseURL: 'https://first-project-a31f1-default-rtdb.firebaseio.com',
    storageBucket: 'first-project-a31f1.appspot.com',
    iosBundleId: 'com.example.app003.RunnerTests',
  );
}
